# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'AleStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AleStore

  target 'AleStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AleStoreUITests' do
    # Pods for testing
  end

end

target 'Data' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Data

  target 'DataTests' do
    # Pods for testing
  end

end

target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain

end

target 'Infra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Infra

  target 'InfraTests' do
    # Pods for testing
  end

end
